-- Converge discussion board. Run this once in the Supabase SQL editor.
-- Generated by scripts/build-forum-sql.mjs; word list from LDNOOBW (CC-BY-4.0).

create table if not exists public.banned_words (
  word text primary key,
  norm text not null,
  squeezed text not null
);

-- lowercase, strip accents, undo leetspeak, keep letters, join spaced-out single letters
create or replace function public.converge_norm(t text) returns text
language plpgsql immutable as $$
declare x text; tok text; res text := ''; prev_single boolean := false;
begin
  x := lower(coalesce(t, ''));
  x := translate(x, 'àáâãäåèéêëìíîïòóôõöùúûüñç', 'aaaaaaeeeeiiiiooooouuuunc');
  x := translate(x, '01!|3@457+89$', 'oiiieaasttbgs');
  x := btrim(regexp_replace(x, '[^a-z]+', ' ', 'g'));
  -- join runs of single letters: "f u c k" -> "fuck"
  foreach tok in array string_to_array(x, ' ') loop
    continue when tok = '';
    if length(tok) = 1 and prev_single then res := res || tok;
    else res := res || case when res = '' then '' else ' ' end || tok; end if;
    prev_single := length(tok) = 1;
  end loop;
  return res;
end $$;

create or replace function public.converge_is_profane(t text) returns boolean
language plpgsql stable as $$
declare n text; s text; j text; r text; -- roots below are blocked even inside longer words
begin
  n := public.converge_norm(t);
  s := regexp_replace(n, '(.)\1+', '\1', 'g');
  j := replace(s, ' ', '');
  -- stretched spellings: squeeze only the words that repeat a letter, so "but" never matches "butt"
  select coalesce(string_agg(regexp_replace(w, '(.)\1+', '\1', 'g'), ' '), '') into r from unnest(string_to_array(n, ' ')) w where w ~ '(.)\1';
  return exists (
    select 1 from public.banned_words b
    where position(' ' || b.norm || ' ' in ' ' || n || ' ') > 0
       or (position(' ' in b.squeezed) = 0 and position(' ' || b.squeezed || ' ' in ' ' || r || ' ') > 0)
       or (length(b.squeezed) >= 5 and position(' ' in b.squeezed) = 0 and position(b.squeezed in j) > 0)
  ) or j ~ '(fuck|fuk|shit|bitch|nigg|whore|motherf|cocksuck|dickhead|asshole|bastard|retard)';
end $$;

create table if not exists public.forum_posts (
  id bigint generated always as identity primary key,
  ticker text not null check (ticker ~ '^[A-Z.]{1,6}$'),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 30),
  body text not null check (char_length(btrim(body)) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists forum_posts_ticker_created on public.forum_posts (ticker, created_at desc);

-- membership tiers: everyone signs up as 'free'; only premium members can post
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  tier text not null default 'free' check (tier in ('free', 'premium')),
  premium_until timestamptz,
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
drop policy if exists "members read their own profile" on public.profiles;
create policy "members read their own profile" on public.profiles for select to authenticated using (id = auth.uid());
-- no insert/update policies: tiers change only from the dashboard, SQL, or a payment webhook using the service role

create or replace function public.converge_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id) values (new.id) on conflict (id) do nothing;
  return new;
end $$;
drop trigger if exists converge_new_user on auth.users;
create trigger converge_new_user after insert on auth.users for each row execute function public.converge_new_user();
insert into public.profiles (id) select id from auth.users on conflict (id) do nothing;

-- master switch: while premium_required is false (testing), every signed-in member counts as premium.
-- Turn the paywall on with: update public.converge_settings set premium_required = true;
create table if not exists public.converge_settings (
  id int primary key default 1 check (id = 1),
  premium_required boolean not null default false
);
insert into public.converge_settings (id) values (1) on conflict (id) do nothing;
alter table public.converge_settings enable row level security;
drop policy if exists "anyone can read settings" on public.converge_settings;
create policy "anyone can read settings" on public.converge_settings for select using (true);

create or replace function public.converge_is_premium(uid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select uid is not null and (
    not coalesce((select premium_required from public.converge_settings where id = 1), false)
    or exists (select 1 from public.profiles p where p.id = uid and p.tier = 'premium' and (p.premium_until is null or p.premium_until > now())));
$$;

alter table public.forum_posts enable row level security;
drop policy if exists "anyone can read posts" on public.forum_posts;
create policy "anyone can read posts" on public.forum_posts for select using (true);
drop policy if exists "signed-in users post as themselves" on public.forum_posts;
create policy "signed-in users post as themselves" on public.forum_posts for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "premium members post as themselves" on public.forum_posts;
drop policy if exists "signed-in users post as themselves" on public.forum_posts;
create policy "premium members post as themselves" on public.forum_posts for insert to authenticated with check (user_id = auth.uid() and public.converge_is_premium(auth.uid()));
drop policy if exists "authors delete their posts" on public.forum_posts;
create policy "authors delete their posts" on public.forum_posts for delete to authenticated using (user_id = auth.uid());

alter table public.banned_words enable row level security; -- not readable through the API

-- block foul language and flooding, server-side
create or replace function public.converge_check_post() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  new.user_id := auth.uid();
  new.body := btrim(new.body);
  if not public.converge_is_premium(new.user_id) then
    raise exception 'Posting is a Premium feature.' using errcode = 'P0001';
  end if;
  if public.converge_is_profane(new.body) or public.converge_is_profane(new.display_name) then
    raise exception 'Post blocked: please keep the language civil.' using errcode = 'P0001';
  end if;
  if (select count(*) from public.forum_posts where user_id = new.user_id and created_at > now() - interval '1 minute') >= 5 then
    raise exception 'You are posting too fast. Please wait a minute.' using errcode = 'P0001';
  end if;
  return new;
end $$;
drop trigger if exists converge_check_post on public.forum_posts;
create trigger converge_check_post before insert on public.forum_posts for each row execute function public.converge_check_post();

-- account sync: one private document per member (portfolio lots, theses, watchlist, settings)
create table if not exists public.user_state (
  user_id uuid primary key default auth.uid() references auth.users (id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  device text,
  updated_at timestamptz not null default now(),
  constraint user_state_size check (octet_length(data::text) < 2000000)
);
alter table public.user_state enable row level security;
drop policy if exists "members read their own state" on public.user_state;
create policy "members read their own state" on public.user_state for select to authenticated using (user_id = auth.uid());
drop policy if exists "members create their own state" on public.user_state;
create policy "members create their own state" on public.user_state for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "members update their own state" on public.user_state;
create policy "members update their own state" on public.user_state for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
grant select, insert, update on public.user_state to authenticated;

-- members can delete their own account (posts, profile and synced data go with it)
create or replace function public.converge_delete_me() returns void
language plpgsql security definer set search_path = public, auth as $$
begin
  if auth.uid() is null then raise exception 'Not signed in.' using errcode = 'P0001'; end if;
  delete from auth.users where id = auth.uid();
end $$;
revoke all on function public.converge_delete_me() from public, anon;
grant execute on function public.converge_delete_me() to authenticated;

-- word list
insert into public.banned_words (word, norm, squeezed) values
  ('2g1c', public.converge_norm('2g1c'), regexp_replace(public.converge_norm('2g1c'), '(.)\1+', '\1', 'g')),
  ('2 girls 1 cup', public.converge_norm('2 girls 1 cup'), regexp_replace(public.converge_norm('2 girls 1 cup'), '(.)\1+', '\1', 'g')),
  ('acrotomophilia', public.converge_norm('acrotomophilia'), regexp_replace(public.converge_norm('acrotomophilia'), '(.)\1+', '\1', 'g')),
  ('alabama hot pocket', public.converge_norm('alabama hot pocket'), regexp_replace(public.converge_norm('alabama hot pocket'), '(.)\1+', '\1', 'g')),
  ('alaskan pipeline', public.converge_norm('alaskan pipeline'), regexp_replace(public.converge_norm('alaskan pipeline'), '(.)\1+', '\1', 'g')),
  ('anal', public.converge_norm('anal'), regexp_replace(public.converge_norm('anal'), '(.)\1+', '\1', 'g')),
  ('anilingus', public.converge_norm('anilingus'), regexp_replace(public.converge_norm('anilingus'), '(.)\1+', '\1', 'g')),
  ('anus', public.converge_norm('anus'), regexp_replace(public.converge_norm('anus'), '(.)\1+', '\1', 'g')),
  ('apeshit', public.converge_norm('apeshit'), regexp_replace(public.converge_norm('apeshit'), '(.)\1+', '\1', 'g')),
  ('arsehole', public.converge_norm('arsehole'), regexp_replace(public.converge_norm('arsehole'), '(.)\1+', '\1', 'g')),
  ('ass', public.converge_norm('ass'), regexp_replace(public.converge_norm('ass'), '(.)\1+', '\1', 'g')),
  ('asshole', public.converge_norm('asshole'), regexp_replace(public.converge_norm('asshole'), '(.)\1+', '\1', 'g')),
  ('assmunch', public.converge_norm('assmunch'), regexp_replace(public.converge_norm('assmunch'), '(.)\1+', '\1', 'g')),
  ('auto erotic', public.converge_norm('auto erotic'), regexp_replace(public.converge_norm('auto erotic'), '(.)\1+', '\1', 'g')),
  ('autoerotic', public.converge_norm('autoerotic'), regexp_replace(public.converge_norm('autoerotic'), '(.)\1+', '\1', 'g')),
  ('babeland', public.converge_norm('babeland'), regexp_replace(public.converge_norm('babeland'), '(.)\1+', '\1', 'g')),
  ('baby batter', public.converge_norm('baby batter'), regexp_replace(public.converge_norm('baby batter'), '(.)\1+', '\1', 'g')),
  ('baby juice', public.converge_norm('baby juice'), regexp_replace(public.converge_norm('baby juice'), '(.)\1+', '\1', 'g')),
  ('ball gag', public.converge_norm('ball gag'), regexp_replace(public.converge_norm('ball gag'), '(.)\1+', '\1', 'g')),
  ('ball gravy', public.converge_norm('ball gravy'), regexp_replace(public.converge_norm('ball gravy'), '(.)\1+', '\1', 'g')),
  ('ball kicking', public.converge_norm('ball kicking'), regexp_replace(public.converge_norm('ball kicking'), '(.)\1+', '\1', 'g')),
  ('ball licking', public.converge_norm('ball licking'), regexp_replace(public.converge_norm('ball licking'), '(.)\1+', '\1', 'g')),
  ('ball sack', public.converge_norm('ball sack'), regexp_replace(public.converge_norm('ball sack'), '(.)\1+', '\1', 'g')),
  ('ball sucking', public.converge_norm('ball sucking'), regexp_replace(public.converge_norm('ball sucking'), '(.)\1+', '\1', 'g')),
  ('bangbros', public.converge_norm('bangbros'), regexp_replace(public.converge_norm('bangbros'), '(.)\1+', '\1', 'g')),
  ('bangbus', public.converge_norm('bangbus'), regexp_replace(public.converge_norm('bangbus'), '(.)\1+', '\1', 'g')),
  ('bareback', public.converge_norm('bareback'), regexp_replace(public.converge_norm('bareback'), '(.)\1+', '\1', 'g')),
  ('barely legal', public.converge_norm('barely legal'), regexp_replace(public.converge_norm('barely legal'), '(.)\1+', '\1', 'g')),
  ('barenaked', public.converge_norm('barenaked'), regexp_replace(public.converge_norm('barenaked'), '(.)\1+', '\1', 'g')),
  ('bastard', public.converge_norm('bastard'), regexp_replace(public.converge_norm('bastard'), '(.)\1+', '\1', 'g')),
  ('bastardo', public.converge_norm('bastardo'), regexp_replace(public.converge_norm('bastardo'), '(.)\1+', '\1', 'g')),
  ('bastinado', public.converge_norm('bastinado'), regexp_replace(public.converge_norm('bastinado'), '(.)\1+', '\1', 'g')),
  ('bbw', public.converge_norm('bbw'), regexp_replace(public.converge_norm('bbw'), '(.)\1+', '\1', 'g')),
  ('bdsm', public.converge_norm('bdsm'), regexp_replace(public.converge_norm('bdsm'), '(.)\1+', '\1', 'g')),
  ('beaner', public.converge_norm('beaner'), regexp_replace(public.converge_norm('beaner'), '(.)\1+', '\1', 'g')),
  ('beaners', public.converge_norm('beaners'), regexp_replace(public.converge_norm('beaners'), '(.)\1+', '\1', 'g')),
  ('beaver cleaver', public.converge_norm('beaver cleaver'), regexp_replace(public.converge_norm('beaver cleaver'), '(.)\1+', '\1', 'g')),
  ('beaver lips', public.converge_norm('beaver lips'), regexp_replace(public.converge_norm('beaver lips'), '(.)\1+', '\1', 'g')),
  ('beastiality', public.converge_norm('beastiality'), regexp_replace(public.converge_norm('beastiality'), '(.)\1+', '\1', 'g')),
  ('bestiality', public.converge_norm('bestiality'), regexp_replace(public.converge_norm('bestiality'), '(.)\1+', '\1', 'g')),
  ('big black', public.converge_norm('big black'), regexp_replace(public.converge_norm('big black'), '(.)\1+', '\1', 'g')),
  ('big breasts', public.converge_norm('big breasts'), regexp_replace(public.converge_norm('big breasts'), '(.)\1+', '\1', 'g')),
  ('big knockers', public.converge_norm('big knockers'), regexp_replace(public.converge_norm('big knockers'), '(.)\1+', '\1', 'g')),
  ('big tits', public.converge_norm('big tits'), regexp_replace(public.converge_norm('big tits'), '(.)\1+', '\1', 'g')),
  ('bimbos', public.converge_norm('bimbos'), regexp_replace(public.converge_norm('bimbos'), '(.)\1+', '\1', 'g')),
  ('birdlock', public.converge_norm('birdlock'), regexp_replace(public.converge_norm('birdlock'), '(.)\1+', '\1', 'g')),
  ('bitch', public.converge_norm('bitch'), regexp_replace(public.converge_norm('bitch'), '(.)\1+', '\1', 'g')),
  ('bitches', public.converge_norm('bitches'), regexp_replace(public.converge_norm('bitches'), '(.)\1+', '\1', 'g')),
  ('black cock', public.converge_norm('black cock'), regexp_replace(public.converge_norm('black cock'), '(.)\1+', '\1', 'g')),
  ('blonde action', public.converge_norm('blonde action'), regexp_replace(public.converge_norm('blonde action'), '(.)\1+', '\1', 'g')),
  ('blonde on blonde action', public.converge_norm('blonde on blonde action'), regexp_replace(public.converge_norm('blonde on blonde action'), '(.)\1+', '\1', 'g')),
  ('blowjob', public.converge_norm('blowjob'), regexp_replace(public.converge_norm('blowjob'), '(.)\1+', '\1', 'g')),
  ('blow job', public.converge_norm('blow job'), regexp_replace(public.converge_norm('blow job'), '(.)\1+', '\1', 'g')),
  ('blow your load', public.converge_norm('blow your load'), regexp_replace(public.converge_norm('blow your load'), '(.)\1+', '\1', 'g')),
  ('blue waffle', public.converge_norm('blue waffle'), regexp_replace(public.converge_norm('blue waffle'), '(.)\1+', '\1', 'g')),
  ('blumpkin', public.converge_norm('blumpkin'), regexp_replace(public.converge_norm('blumpkin'), '(.)\1+', '\1', 'g')),
  ('bollocks', public.converge_norm('bollocks'), regexp_replace(public.converge_norm('bollocks'), '(.)\1+', '\1', 'g')),
  ('bondage', public.converge_norm('bondage'), regexp_replace(public.converge_norm('bondage'), '(.)\1+', '\1', 'g')),
  ('boner', public.converge_norm('boner'), regexp_replace(public.converge_norm('boner'), '(.)\1+', '\1', 'g')),
  ('boob', public.converge_norm('boob'), regexp_replace(public.converge_norm('boob'), '(.)\1+', '\1', 'g')),
  ('boobs', public.converge_norm('boobs'), regexp_replace(public.converge_norm('boobs'), '(.)\1+', '\1', 'g')),
  ('booty call', public.converge_norm('booty call'), regexp_replace(public.converge_norm('booty call'), '(.)\1+', '\1', 'g')),
  ('brown showers', public.converge_norm('brown showers'), regexp_replace(public.converge_norm('brown showers'), '(.)\1+', '\1', 'g')),
  ('brunette action', public.converge_norm('brunette action'), regexp_replace(public.converge_norm('brunette action'), '(.)\1+', '\1', 'g')),
  ('bukkake', public.converge_norm('bukkake'), regexp_replace(public.converge_norm('bukkake'), '(.)\1+', '\1', 'g')),
  ('bulldyke', public.converge_norm('bulldyke'), regexp_replace(public.converge_norm('bulldyke'), '(.)\1+', '\1', 'g')),
  ('bullet vibe', public.converge_norm('bullet vibe'), regexp_replace(public.converge_norm('bullet vibe'), '(.)\1+', '\1', 'g')),
  ('bullshit', public.converge_norm('bullshit'), regexp_replace(public.converge_norm('bullshit'), '(.)\1+', '\1', 'g')),
  ('bung hole', public.converge_norm('bung hole'), regexp_replace(public.converge_norm('bung hole'), '(.)\1+', '\1', 'g')),
  ('bunghole', public.converge_norm('bunghole'), regexp_replace(public.converge_norm('bunghole'), '(.)\1+', '\1', 'g')),
  ('busty', public.converge_norm('busty'), regexp_replace(public.converge_norm('busty'), '(.)\1+', '\1', 'g')),
  ('butt', public.converge_norm('butt'), regexp_replace(public.converge_norm('butt'), '(.)\1+', '\1', 'g')),
  ('buttcheeks', public.converge_norm('buttcheeks'), regexp_replace(public.converge_norm('buttcheeks'), '(.)\1+', '\1', 'g')),
  ('butthole', public.converge_norm('butthole'), regexp_replace(public.converge_norm('butthole'), '(.)\1+', '\1', 'g')),
  ('camel toe', public.converge_norm('camel toe'), regexp_replace(public.converge_norm('camel toe'), '(.)\1+', '\1', 'g')),
  ('camgirl', public.converge_norm('camgirl'), regexp_replace(public.converge_norm('camgirl'), '(.)\1+', '\1', 'g')),
  ('camslut', public.converge_norm('camslut'), regexp_replace(public.converge_norm('camslut'), '(.)\1+', '\1', 'g')),
  ('camwhore', public.converge_norm('camwhore'), regexp_replace(public.converge_norm('camwhore'), '(.)\1+', '\1', 'g')),
  ('carpet muncher', public.converge_norm('carpet muncher'), regexp_replace(public.converge_norm('carpet muncher'), '(.)\1+', '\1', 'g')),
  ('carpetmuncher', public.converge_norm('carpetmuncher'), regexp_replace(public.converge_norm('carpetmuncher'), '(.)\1+', '\1', 'g')),
  ('chocolate rosebuds', public.converge_norm('chocolate rosebuds'), regexp_replace(public.converge_norm('chocolate rosebuds'), '(.)\1+', '\1', 'g')),
  ('cialis', public.converge_norm('cialis'), regexp_replace(public.converge_norm('cialis'), '(.)\1+', '\1', 'g')),
  ('circlejerk', public.converge_norm('circlejerk'), regexp_replace(public.converge_norm('circlejerk'), '(.)\1+', '\1', 'g')),
  ('cleveland steamer', public.converge_norm('cleveland steamer'), regexp_replace(public.converge_norm('cleveland steamer'), '(.)\1+', '\1', 'g')),
  ('clit', public.converge_norm('clit'), regexp_replace(public.converge_norm('clit'), '(.)\1+', '\1', 'g')),
  ('clitoris', public.converge_norm('clitoris'), regexp_replace(public.converge_norm('clitoris'), '(.)\1+', '\1', 'g')),
  ('clover clamps', public.converge_norm('clover clamps'), regexp_replace(public.converge_norm('clover clamps'), '(.)\1+', '\1', 'g')),
  ('clusterfuck', public.converge_norm('clusterfuck'), regexp_replace(public.converge_norm('clusterfuck'), '(.)\1+', '\1', 'g')),
  ('cock', public.converge_norm('cock'), regexp_replace(public.converge_norm('cock'), '(.)\1+', '\1', 'g')),
  ('cocks', public.converge_norm('cocks'), regexp_replace(public.converge_norm('cocks'), '(.)\1+', '\1', 'g')),
  ('coprolagnia', public.converge_norm('coprolagnia'), regexp_replace(public.converge_norm('coprolagnia'), '(.)\1+', '\1', 'g')),
  ('coprophilia', public.converge_norm('coprophilia'), regexp_replace(public.converge_norm('coprophilia'), '(.)\1+', '\1', 'g')),
  ('cornhole', public.converge_norm('cornhole'), regexp_replace(public.converge_norm('cornhole'), '(.)\1+', '\1', 'g')),
  ('coon', public.converge_norm('coon'), regexp_replace(public.converge_norm('coon'), '(.)\1+', '\1', 'g')),
  ('coons', public.converge_norm('coons'), regexp_replace(public.converge_norm('coons'), '(.)\1+', '\1', 'g')),
  ('creampie', public.converge_norm('creampie'), regexp_replace(public.converge_norm('creampie'), '(.)\1+', '\1', 'g')),
  ('cum', public.converge_norm('cum'), regexp_replace(public.converge_norm('cum'), '(.)\1+', '\1', 'g')),
  ('cumming', public.converge_norm('cumming'), regexp_replace(public.converge_norm('cumming'), '(.)\1+', '\1', 'g')),
  ('cumshot', public.converge_norm('cumshot'), regexp_replace(public.converge_norm('cumshot'), '(.)\1+', '\1', 'g')),
  ('cumshots', public.converge_norm('cumshots'), regexp_replace(public.converge_norm('cumshots'), '(.)\1+', '\1', 'g')),
  ('cunnilingus', public.converge_norm('cunnilingus'), regexp_replace(public.converge_norm('cunnilingus'), '(.)\1+', '\1', 'g')),
  ('cunt', public.converge_norm('cunt'), regexp_replace(public.converge_norm('cunt'), '(.)\1+', '\1', 'g')),
  ('darkie', public.converge_norm('darkie'), regexp_replace(public.converge_norm('darkie'), '(.)\1+', '\1', 'g')),
  ('date rape', public.converge_norm('date rape'), regexp_replace(public.converge_norm('date rape'), '(.)\1+', '\1', 'g')),
  ('daterape', public.converge_norm('daterape'), regexp_replace(public.converge_norm('daterape'), '(.)\1+', '\1', 'g')),
  ('deep throat', public.converge_norm('deep throat'), regexp_replace(public.converge_norm('deep throat'), '(.)\1+', '\1', 'g')),
  ('deepthroat', public.converge_norm('deepthroat'), regexp_replace(public.converge_norm('deepthroat'), '(.)\1+', '\1', 'g')),
  ('dendrophilia', public.converge_norm('dendrophilia'), regexp_replace(public.converge_norm('dendrophilia'), '(.)\1+', '\1', 'g')),
  ('dick', public.converge_norm('dick'), regexp_replace(public.converge_norm('dick'), '(.)\1+', '\1', 'g')),
  ('dildo', public.converge_norm('dildo'), regexp_replace(public.converge_norm('dildo'), '(.)\1+', '\1', 'g')),
  ('dingleberry', public.converge_norm('dingleberry'), regexp_replace(public.converge_norm('dingleberry'), '(.)\1+', '\1', 'g')),
  ('dingleberries', public.converge_norm('dingleberries'), regexp_replace(public.converge_norm('dingleberries'), '(.)\1+', '\1', 'g')),
  ('dirty pillows', public.converge_norm('dirty pillows'), regexp_replace(public.converge_norm('dirty pillows'), '(.)\1+', '\1', 'g')),
  ('dirty sanchez', public.converge_norm('dirty sanchez'), regexp_replace(public.converge_norm('dirty sanchez'), '(.)\1+', '\1', 'g')),
  ('doggie style', public.converge_norm('doggie style'), regexp_replace(public.converge_norm('doggie style'), '(.)\1+', '\1', 'g')),
  ('doggiestyle', public.converge_norm('doggiestyle'), regexp_replace(public.converge_norm('doggiestyle'), '(.)\1+', '\1', 'g')),
  ('doggy style', public.converge_norm('doggy style'), regexp_replace(public.converge_norm('doggy style'), '(.)\1+', '\1', 'g')),
  ('doggystyle', public.converge_norm('doggystyle'), regexp_replace(public.converge_norm('doggystyle'), '(.)\1+', '\1', 'g')),
  ('dog style', public.converge_norm('dog style'), regexp_replace(public.converge_norm('dog style'), '(.)\1+', '\1', 'g')),
  ('dolcett', public.converge_norm('dolcett'), regexp_replace(public.converge_norm('dolcett'), '(.)\1+', '\1', 'g')),
  ('domination', public.converge_norm('domination'), regexp_replace(public.converge_norm('domination'), '(.)\1+', '\1', 'g')),
  ('dominatrix', public.converge_norm('dominatrix'), regexp_replace(public.converge_norm('dominatrix'), '(.)\1+', '\1', 'g')),
  ('dommes', public.converge_norm('dommes'), regexp_replace(public.converge_norm('dommes'), '(.)\1+', '\1', 'g')),
  ('donkey punch', public.converge_norm('donkey punch'), regexp_replace(public.converge_norm('donkey punch'), '(.)\1+', '\1', 'g')),
  ('double dong', public.converge_norm('double dong'), regexp_replace(public.converge_norm('double dong'), '(.)\1+', '\1', 'g')),
  ('double penetration', public.converge_norm('double penetration'), regexp_replace(public.converge_norm('double penetration'), '(.)\1+', '\1', 'g')),
  ('dp action', public.converge_norm('dp action'), regexp_replace(public.converge_norm('dp action'), '(.)\1+', '\1', 'g')),
  ('dry hump', public.converge_norm('dry hump'), regexp_replace(public.converge_norm('dry hump'), '(.)\1+', '\1', 'g')),
  ('dvda', public.converge_norm('dvda'), regexp_replace(public.converge_norm('dvda'), '(.)\1+', '\1', 'g')),
  ('eat my ass', public.converge_norm('eat my ass'), regexp_replace(public.converge_norm('eat my ass'), '(.)\1+', '\1', 'g')),
  ('ecchi', public.converge_norm('ecchi'), regexp_replace(public.converge_norm('ecchi'), '(.)\1+', '\1', 'g')),
  ('ejaculation', public.converge_norm('ejaculation'), regexp_replace(public.converge_norm('ejaculation'), '(.)\1+', '\1', 'g')),
  ('erotic', public.converge_norm('erotic'), regexp_replace(public.converge_norm('erotic'), '(.)\1+', '\1', 'g')),
  ('erotism', public.converge_norm('erotism'), regexp_replace(public.converge_norm('erotism'), '(.)\1+', '\1', 'g')),
  ('escort', public.converge_norm('escort'), regexp_replace(public.converge_norm('escort'), '(.)\1+', '\1', 'g')),
  ('eunuch', public.converge_norm('eunuch'), regexp_replace(public.converge_norm('eunuch'), '(.)\1+', '\1', 'g')),
  ('fag', public.converge_norm('fag'), regexp_replace(public.converge_norm('fag'), '(.)\1+', '\1', 'g')),
  ('faggot', public.converge_norm('faggot'), regexp_replace(public.converge_norm('faggot'), '(.)\1+', '\1', 'g')),
  ('fecal', public.converge_norm('fecal'), regexp_replace(public.converge_norm('fecal'), '(.)\1+', '\1', 'g')),
  ('felch', public.converge_norm('felch'), regexp_replace(public.converge_norm('felch'), '(.)\1+', '\1', 'g')),
  ('fellatio', public.converge_norm('fellatio'), regexp_replace(public.converge_norm('fellatio'), '(.)\1+', '\1', 'g')),
  ('feltch', public.converge_norm('feltch'), regexp_replace(public.converge_norm('feltch'), '(.)\1+', '\1', 'g')),
  ('female squirting', public.converge_norm('female squirting'), regexp_replace(public.converge_norm('female squirting'), '(.)\1+', '\1', 'g')),
  ('femdom', public.converge_norm('femdom'), regexp_replace(public.converge_norm('femdom'), '(.)\1+', '\1', 'g')),
  ('figging', public.converge_norm('figging'), regexp_replace(public.converge_norm('figging'), '(.)\1+', '\1', 'g')),
  ('fingerbang', public.converge_norm('fingerbang'), regexp_replace(public.converge_norm('fingerbang'), '(.)\1+', '\1', 'g')),
  ('fingering', public.converge_norm('fingering'), regexp_replace(public.converge_norm('fingering'), '(.)\1+', '\1', 'g')),
  ('fisting', public.converge_norm('fisting'), regexp_replace(public.converge_norm('fisting'), '(.)\1+', '\1', 'g')),
  ('foot fetish', public.converge_norm('foot fetish'), regexp_replace(public.converge_norm('foot fetish'), '(.)\1+', '\1', 'g')),
  ('footjob', public.converge_norm('footjob'), regexp_replace(public.converge_norm('footjob'), '(.)\1+', '\1', 'g')),
  ('frotting', public.converge_norm('frotting'), regexp_replace(public.converge_norm('frotting'), '(.)\1+', '\1', 'g')),
  ('fuck', public.converge_norm('fuck'), regexp_replace(public.converge_norm('fuck'), '(.)\1+', '\1', 'g')),
  ('fuck buttons', public.converge_norm('fuck buttons'), regexp_replace(public.converge_norm('fuck buttons'), '(.)\1+', '\1', 'g')),
  ('fuckin', public.converge_norm('fuckin'), regexp_replace(public.converge_norm('fuckin'), '(.)\1+', '\1', 'g')),
  ('fucking', public.converge_norm('fucking'), regexp_replace(public.converge_norm('fucking'), '(.)\1+', '\1', 'g')),
  ('fucktards', public.converge_norm('fucktards'), regexp_replace(public.converge_norm('fucktards'), '(.)\1+', '\1', 'g')),
  ('fudge packer', public.converge_norm('fudge packer'), regexp_replace(public.converge_norm('fudge packer'), '(.)\1+', '\1', 'g')),
  ('fudgepacker', public.converge_norm('fudgepacker'), regexp_replace(public.converge_norm('fudgepacker'), '(.)\1+', '\1', 'g')),
  ('futanari', public.converge_norm('futanari'), regexp_replace(public.converge_norm('futanari'), '(.)\1+', '\1', 'g')),
  ('gangbang', public.converge_norm('gangbang'), regexp_replace(public.converge_norm('gangbang'), '(.)\1+', '\1', 'g')),
  ('gang bang', public.converge_norm('gang bang'), regexp_replace(public.converge_norm('gang bang'), '(.)\1+', '\1', 'g')),
  ('gay sex', public.converge_norm('gay sex'), regexp_replace(public.converge_norm('gay sex'), '(.)\1+', '\1', 'g')),
  ('genitals', public.converge_norm('genitals'), regexp_replace(public.converge_norm('genitals'), '(.)\1+', '\1', 'g')),
  ('giant cock', public.converge_norm('giant cock'), regexp_replace(public.converge_norm('giant cock'), '(.)\1+', '\1', 'g')),
  ('girl on', public.converge_norm('girl on'), regexp_replace(public.converge_norm('girl on'), '(.)\1+', '\1', 'g')),
  ('girl on top', public.converge_norm('girl on top'), regexp_replace(public.converge_norm('girl on top'), '(.)\1+', '\1', 'g')),
  ('girls gone wild', public.converge_norm('girls gone wild'), regexp_replace(public.converge_norm('girls gone wild'), '(.)\1+', '\1', 'g')),
  ('goatcx', public.converge_norm('goatcx'), regexp_replace(public.converge_norm('goatcx'), '(.)\1+', '\1', 'g')),
  ('goatse', public.converge_norm('goatse'), regexp_replace(public.converge_norm('goatse'), '(.)\1+', '\1', 'g')),
  ('god damn', public.converge_norm('god damn'), regexp_replace(public.converge_norm('god damn'), '(.)\1+', '\1', 'g')),
  ('gokkun', public.converge_norm('gokkun'), regexp_replace(public.converge_norm('gokkun'), '(.)\1+', '\1', 'g')),
  ('golden shower', public.converge_norm('golden shower'), regexp_replace(public.converge_norm('golden shower'), '(.)\1+', '\1', 'g')),
  ('goodpoop', public.converge_norm('goodpoop'), regexp_replace(public.converge_norm('goodpoop'), '(.)\1+', '\1', 'g')),
  ('goo girl', public.converge_norm('goo girl'), regexp_replace(public.converge_norm('goo girl'), '(.)\1+', '\1', 'g')),
  ('goregasm', public.converge_norm('goregasm'), regexp_replace(public.converge_norm('goregasm'), '(.)\1+', '\1', 'g')),
  ('grope', public.converge_norm('grope'), regexp_replace(public.converge_norm('grope'), '(.)\1+', '\1', 'g')),
  ('group sex', public.converge_norm('group sex'), regexp_replace(public.converge_norm('group sex'), '(.)\1+', '\1', 'g')),
  ('g-spot', public.converge_norm('g-spot'), regexp_replace(public.converge_norm('g-spot'), '(.)\1+', '\1', 'g')),
  ('guro', public.converge_norm('guro'), regexp_replace(public.converge_norm('guro'), '(.)\1+', '\1', 'g')),
  ('hand job', public.converge_norm('hand job'), regexp_replace(public.converge_norm('hand job'), '(.)\1+', '\1', 'g')),
  ('handjob', public.converge_norm('handjob'), regexp_replace(public.converge_norm('handjob'), '(.)\1+', '\1', 'g')),
  ('hard core', public.converge_norm('hard core'), regexp_replace(public.converge_norm('hard core'), '(.)\1+', '\1', 'g')),
  ('hardcore', public.converge_norm('hardcore'), regexp_replace(public.converge_norm('hardcore'), '(.)\1+', '\1', 'g')),
  ('hentai', public.converge_norm('hentai'), regexp_replace(public.converge_norm('hentai'), '(.)\1+', '\1', 'g')),
  ('homoerotic', public.converge_norm('homoerotic'), regexp_replace(public.converge_norm('homoerotic'), '(.)\1+', '\1', 'g')),
  ('honkey', public.converge_norm('honkey'), regexp_replace(public.converge_norm('honkey'), '(.)\1+', '\1', 'g')),
  ('hooker', public.converge_norm('hooker'), regexp_replace(public.converge_norm('hooker'), '(.)\1+', '\1', 'g')),
  ('horny', public.converge_norm('horny'), regexp_replace(public.converge_norm('horny'), '(.)\1+', '\1', 'g')),
  ('hot carl', public.converge_norm('hot carl'), regexp_replace(public.converge_norm('hot carl'), '(.)\1+', '\1', 'g')),
  ('hot chick', public.converge_norm('hot chick'), regexp_replace(public.converge_norm('hot chick'), '(.)\1+', '\1', 'g')),
  ('how to kill', public.converge_norm('how to kill'), regexp_replace(public.converge_norm('how to kill'), '(.)\1+', '\1', 'g')),
  ('how to murder', public.converge_norm('how to murder'), regexp_replace(public.converge_norm('how to murder'), '(.)\1+', '\1', 'g')),
  ('huge fat', public.converge_norm('huge fat'), regexp_replace(public.converge_norm('huge fat'), '(.)\1+', '\1', 'g')),
  ('humping', public.converge_norm('humping'), regexp_replace(public.converge_norm('humping'), '(.)\1+', '\1', 'g')),
  ('incest', public.converge_norm('incest'), regexp_replace(public.converge_norm('incest'), '(.)\1+', '\1', 'g')),
  ('intercourse', public.converge_norm('intercourse'), regexp_replace(public.converge_norm('intercourse'), '(.)\1+', '\1', 'g')),
  ('jack off', public.converge_norm('jack off'), regexp_replace(public.converge_norm('jack off'), '(.)\1+', '\1', 'g')),
  ('jail bait', public.converge_norm('jail bait'), regexp_replace(public.converge_norm('jail bait'), '(.)\1+', '\1', 'g')),
  ('jailbait', public.converge_norm('jailbait'), regexp_replace(public.converge_norm('jailbait'), '(.)\1+', '\1', 'g')),
  ('jelly donut', public.converge_norm('jelly donut'), regexp_replace(public.converge_norm('jelly donut'), '(.)\1+', '\1', 'g')),
  ('jerk off', public.converge_norm('jerk off'), regexp_replace(public.converge_norm('jerk off'), '(.)\1+', '\1', 'g')),
  ('jigaboo', public.converge_norm('jigaboo'), regexp_replace(public.converge_norm('jigaboo'), '(.)\1+', '\1', 'g')),
  ('jiggaboo', public.converge_norm('jiggaboo'), regexp_replace(public.converge_norm('jiggaboo'), '(.)\1+', '\1', 'g')),
  ('jiggerboo', public.converge_norm('jiggerboo'), regexp_replace(public.converge_norm('jiggerboo'), '(.)\1+', '\1', 'g')),
  ('jizz', public.converge_norm('jizz'), regexp_replace(public.converge_norm('jizz'), '(.)\1+', '\1', 'g')),
  ('juggs', public.converge_norm('juggs'), regexp_replace(public.converge_norm('juggs'), '(.)\1+', '\1', 'g')),
  ('kike', public.converge_norm('kike'), regexp_replace(public.converge_norm('kike'), '(.)\1+', '\1', 'g')),
  ('kinbaku', public.converge_norm('kinbaku'), regexp_replace(public.converge_norm('kinbaku'), '(.)\1+', '\1', 'g')),
  ('kinkster', public.converge_norm('kinkster'), regexp_replace(public.converge_norm('kinkster'), '(.)\1+', '\1', 'g')),
  ('kinky', public.converge_norm('kinky'), regexp_replace(public.converge_norm('kinky'), '(.)\1+', '\1', 'g')),
  ('knobbing', public.converge_norm('knobbing'), regexp_replace(public.converge_norm('knobbing'), '(.)\1+', '\1', 'g')),
  ('leather restraint', public.converge_norm('leather restraint'), regexp_replace(public.converge_norm('leather restraint'), '(.)\1+', '\1', 'g')),
  ('leather straight jacket', public.converge_norm('leather straight jacket'), regexp_replace(public.converge_norm('leather straight jacket'), '(.)\1+', '\1', 'g')),
  ('lemon party', public.converge_norm('lemon party'), regexp_replace(public.converge_norm('lemon party'), '(.)\1+', '\1', 'g')),
  ('livesex', public.converge_norm('livesex'), regexp_replace(public.converge_norm('livesex'), '(.)\1+', '\1', 'g')),
  ('lolita', public.converge_norm('lolita'), regexp_replace(public.converge_norm('lolita'), '(.)\1+', '\1', 'g')),
  ('lovemaking', public.converge_norm('lovemaking'), regexp_replace(public.converge_norm('lovemaking'), '(.)\1+', '\1', 'g')),
  ('make me come', public.converge_norm('make me come'), regexp_replace(public.converge_norm('make me come'), '(.)\1+', '\1', 'g')),
  ('male squirting', public.converge_norm('male squirting'), regexp_replace(public.converge_norm('male squirting'), '(.)\1+', '\1', 'g')),
  ('masturbate', public.converge_norm('masturbate'), regexp_replace(public.converge_norm('masturbate'), '(.)\1+', '\1', 'g')),
  ('masturbating', public.converge_norm('masturbating'), regexp_replace(public.converge_norm('masturbating'), '(.)\1+', '\1', 'g')),
  ('masturbation', public.converge_norm('masturbation'), regexp_replace(public.converge_norm('masturbation'), '(.)\1+', '\1', 'g')),
  ('menage a trois', public.converge_norm('menage a trois'), regexp_replace(public.converge_norm('menage a trois'), '(.)\1+', '\1', 'g')),
  ('milf', public.converge_norm('milf'), regexp_replace(public.converge_norm('milf'), '(.)\1+', '\1', 'g')),
  ('missionary position', public.converge_norm('missionary position'), regexp_replace(public.converge_norm('missionary position'), '(.)\1+', '\1', 'g')),
  ('mong', public.converge_norm('mong'), regexp_replace(public.converge_norm('mong'), '(.)\1+', '\1', 'g')),
  ('motherfucker', public.converge_norm('motherfucker'), regexp_replace(public.converge_norm('motherfucker'), '(.)\1+', '\1', 'g')),
  ('mound of venus', public.converge_norm('mound of venus'), regexp_replace(public.converge_norm('mound of venus'), '(.)\1+', '\1', 'g')),
  ('mr hands', public.converge_norm('mr hands'), regexp_replace(public.converge_norm('mr hands'), '(.)\1+', '\1', 'g')),
  ('muff diver', public.converge_norm('muff diver'), regexp_replace(public.converge_norm('muff diver'), '(.)\1+', '\1', 'g')),
  ('muffdiving', public.converge_norm('muffdiving'), regexp_replace(public.converge_norm('muffdiving'), '(.)\1+', '\1', 'g')),
  ('nambla', public.converge_norm('nambla'), regexp_replace(public.converge_norm('nambla'), '(.)\1+', '\1', 'g')),
  ('nawashi', public.converge_norm('nawashi'), regexp_replace(public.converge_norm('nawashi'), '(.)\1+', '\1', 'g')),
  ('negro', public.converge_norm('negro'), regexp_replace(public.converge_norm('negro'), '(.)\1+', '\1', 'g')),
  ('neonazi', public.converge_norm('neonazi'), regexp_replace(public.converge_norm('neonazi'), '(.)\1+', '\1', 'g')),
  ('nigga', public.converge_norm('nigga'), regexp_replace(public.converge_norm('nigga'), '(.)\1+', '\1', 'g')),
  ('nigger', public.converge_norm('nigger'), regexp_replace(public.converge_norm('nigger'), '(.)\1+', '\1', 'g')),
  ('nig nog', public.converge_norm('nig nog'), regexp_replace(public.converge_norm('nig nog'), '(.)\1+', '\1', 'g')),
  ('nimphomania', public.converge_norm('nimphomania'), regexp_replace(public.converge_norm('nimphomania'), '(.)\1+', '\1', 'g')),
  ('nipple', public.converge_norm('nipple'), regexp_replace(public.converge_norm('nipple'), '(.)\1+', '\1', 'g')),
  ('nipples', public.converge_norm('nipples'), regexp_replace(public.converge_norm('nipples'), '(.)\1+', '\1', 'g')),
  ('nsfw', public.converge_norm('nsfw'), regexp_replace(public.converge_norm('nsfw'), '(.)\1+', '\1', 'g')),
  ('nsfw images', public.converge_norm('nsfw images'), regexp_replace(public.converge_norm('nsfw images'), '(.)\1+', '\1', 'g')),
  ('nude', public.converge_norm('nude'), regexp_replace(public.converge_norm('nude'), '(.)\1+', '\1', 'g')),
  ('nudity', public.converge_norm('nudity'), regexp_replace(public.converge_norm('nudity'), '(.)\1+', '\1', 'g')),
  ('nutten', public.converge_norm('nutten'), regexp_replace(public.converge_norm('nutten'), '(.)\1+', '\1', 'g')),
  ('nympho', public.converge_norm('nympho'), regexp_replace(public.converge_norm('nympho'), '(.)\1+', '\1', 'g')),
  ('nymphomania', public.converge_norm('nymphomania'), regexp_replace(public.converge_norm('nymphomania'), '(.)\1+', '\1', 'g')),
  ('octopussy', public.converge_norm('octopussy'), regexp_replace(public.converge_norm('octopussy'), '(.)\1+', '\1', 'g')),
  ('omorashi', public.converge_norm('omorashi'), regexp_replace(public.converge_norm('omorashi'), '(.)\1+', '\1', 'g')),
  ('one cup two girls', public.converge_norm('one cup two girls'), regexp_replace(public.converge_norm('one cup two girls'), '(.)\1+', '\1', 'g')),
  ('one guy one jar', public.converge_norm('one guy one jar'), regexp_replace(public.converge_norm('one guy one jar'), '(.)\1+', '\1', 'g')),
  ('orgasm', public.converge_norm('orgasm'), regexp_replace(public.converge_norm('orgasm'), '(.)\1+', '\1', 'g')),
  ('orgy', public.converge_norm('orgy'), regexp_replace(public.converge_norm('orgy'), '(.)\1+', '\1', 'g')),
  ('paedophile', public.converge_norm('paedophile'), regexp_replace(public.converge_norm('paedophile'), '(.)\1+', '\1', 'g')),
  ('paki', public.converge_norm('paki'), regexp_replace(public.converge_norm('paki'), '(.)\1+', '\1', 'g')),
  ('panties', public.converge_norm('panties'), regexp_replace(public.converge_norm('panties'), '(.)\1+', '\1', 'g')),
  ('panty', public.converge_norm('panty'), regexp_replace(public.converge_norm('panty'), '(.)\1+', '\1', 'g')),
  ('pedobear', public.converge_norm('pedobear'), regexp_replace(public.converge_norm('pedobear'), '(.)\1+', '\1', 'g')),
  ('pedophile', public.converge_norm('pedophile'), regexp_replace(public.converge_norm('pedophile'), '(.)\1+', '\1', 'g')),
  ('pegging', public.converge_norm('pegging'), regexp_replace(public.converge_norm('pegging'), '(.)\1+', '\1', 'g')),
  ('penis', public.converge_norm('penis'), regexp_replace(public.converge_norm('penis'), '(.)\1+', '\1', 'g')),
  ('phone sex', public.converge_norm('phone sex'), regexp_replace(public.converge_norm('phone sex'), '(.)\1+', '\1', 'g')),
  ('piece of shit', public.converge_norm('piece of shit'), regexp_replace(public.converge_norm('piece of shit'), '(.)\1+', '\1', 'g')),
  ('pikey', public.converge_norm('pikey'), regexp_replace(public.converge_norm('pikey'), '(.)\1+', '\1', 'g')),
  ('pissing', public.converge_norm('pissing'), regexp_replace(public.converge_norm('pissing'), '(.)\1+', '\1', 'g')),
  ('piss pig', public.converge_norm('piss pig'), regexp_replace(public.converge_norm('piss pig'), '(.)\1+', '\1', 'g')),
  ('pisspig', public.converge_norm('pisspig'), regexp_replace(public.converge_norm('pisspig'), '(.)\1+', '\1', 'g')),
  ('playboy', public.converge_norm('playboy'), regexp_replace(public.converge_norm('playboy'), '(.)\1+', '\1', 'g')),
  ('pleasure chest', public.converge_norm('pleasure chest'), regexp_replace(public.converge_norm('pleasure chest'), '(.)\1+', '\1', 'g')),
  ('pole smoker', public.converge_norm('pole smoker'), regexp_replace(public.converge_norm('pole smoker'), '(.)\1+', '\1', 'g')),
  ('ponyplay', public.converge_norm('ponyplay'), regexp_replace(public.converge_norm('ponyplay'), '(.)\1+', '\1', 'g')),
  ('poof', public.converge_norm('poof'), regexp_replace(public.converge_norm('poof'), '(.)\1+', '\1', 'g')),
  ('poon', public.converge_norm('poon'), regexp_replace(public.converge_norm('poon'), '(.)\1+', '\1', 'g')),
  ('poontang', public.converge_norm('poontang'), regexp_replace(public.converge_norm('poontang'), '(.)\1+', '\1', 'g')),
  ('punany', public.converge_norm('punany'), regexp_replace(public.converge_norm('punany'), '(.)\1+', '\1', 'g')),
  ('poop chute', public.converge_norm('poop chute'), regexp_replace(public.converge_norm('poop chute'), '(.)\1+', '\1', 'g')),
  ('poopchute', public.converge_norm('poopchute'), regexp_replace(public.converge_norm('poopchute'), '(.)\1+', '\1', 'g')),
  ('porn', public.converge_norm('porn'), regexp_replace(public.converge_norm('porn'), '(.)\1+', '\1', 'g')),
  ('porno', public.converge_norm('porno'), regexp_replace(public.converge_norm('porno'), '(.)\1+', '\1', 'g')),
  ('pornography', public.converge_norm('pornography'), regexp_replace(public.converge_norm('pornography'), '(.)\1+', '\1', 'g')),
  ('prince albert piercing', public.converge_norm('prince albert piercing'), regexp_replace(public.converge_norm('prince albert piercing'), '(.)\1+', '\1', 'g')),
  ('pthc', public.converge_norm('pthc'), regexp_replace(public.converge_norm('pthc'), '(.)\1+', '\1', 'g')),
  ('pubes', public.converge_norm('pubes'), regexp_replace(public.converge_norm('pubes'), '(.)\1+', '\1', 'g')),
  ('pussy', public.converge_norm('pussy'), regexp_replace(public.converge_norm('pussy'), '(.)\1+', '\1', 'g')),
  ('queaf', public.converge_norm('queaf'), regexp_replace(public.converge_norm('queaf'), '(.)\1+', '\1', 'g')),
  ('queef', public.converge_norm('queef'), regexp_replace(public.converge_norm('queef'), '(.)\1+', '\1', 'g')),
  ('quim', public.converge_norm('quim'), regexp_replace(public.converge_norm('quim'), '(.)\1+', '\1', 'g')),
  ('raghead', public.converge_norm('raghead'), regexp_replace(public.converge_norm('raghead'), '(.)\1+', '\1', 'g')),
  ('raging boner', public.converge_norm('raging boner'), regexp_replace(public.converge_norm('raging boner'), '(.)\1+', '\1', 'g')),
  ('rape', public.converge_norm('rape'), regexp_replace(public.converge_norm('rape'), '(.)\1+', '\1', 'g')),
  ('raping', public.converge_norm('raping'), regexp_replace(public.converge_norm('raping'), '(.)\1+', '\1', 'g')),
  ('rapist', public.converge_norm('rapist'), regexp_replace(public.converge_norm('rapist'), '(.)\1+', '\1', 'g')),
  ('rectum', public.converge_norm('rectum'), regexp_replace(public.converge_norm('rectum'), '(.)\1+', '\1', 'g')),
  ('reverse cowgirl', public.converge_norm('reverse cowgirl'), regexp_replace(public.converge_norm('reverse cowgirl'), '(.)\1+', '\1', 'g')),
  ('rimjob', public.converge_norm('rimjob'), regexp_replace(public.converge_norm('rimjob'), '(.)\1+', '\1', 'g')),
  ('rimming', public.converge_norm('rimming'), regexp_replace(public.converge_norm('rimming'), '(.)\1+', '\1', 'g')),
  ('rosy palm', public.converge_norm('rosy palm'), regexp_replace(public.converge_norm('rosy palm'), '(.)\1+', '\1', 'g')),
  ('rosy palm and her 5 sisters', public.converge_norm('rosy palm and her 5 sisters'), regexp_replace(public.converge_norm('rosy palm and her 5 sisters'), '(.)\1+', '\1', 'g')),
  ('rusty trombone', public.converge_norm('rusty trombone'), regexp_replace(public.converge_norm('rusty trombone'), '(.)\1+', '\1', 'g')),
  ('sadism', public.converge_norm('sadism'), regexp_replace(public.converge_norm('sadism'), '(.)\1+', '\1', 'g')),
  ('santorum', public.converge_norm('santorum'), regexp_replace(public.converge_norm('santorum'), '(.)\1+', '\1', 'g')),
  ('scat', public.converge_norm('scat'), regexp_replace(public.converge_norm('scat'), '(.)\1+', '\1', 'g')),
  ('schlong', public.converge_norm('schlong'), regexp_replace(public.converge_norm('schlong'), '(.)\1+', '\1', 'g')),
  ('scissoring', public.converge_norm('scissoring'), regexp_replace(public.converge_norm('scissoring'), '(.)\1+', '\1', 'g')),
  ('semen', public.converge_norm('semen'), regexp_replace(public.converge_norm('semen'), '(.)\1+', '\1', 'g')),
  ('sex', public.converge_norm('sex'), regexp_replace(public.converge_norm('sex'), '(.)\1+', '\1', 'g')),
  ('sexcam', public.converge_norm('sexcam'), regexp_replace(public.converge_norm('sexcam'), '(.)\1+', '\1', 'g')),
  ('sexo', public.converge_norm('sexo'), regexp_replace(public.converge_norm('sexo'), '(.)\1+', '\1', 'g')),
  ('sexy', public.converge_norm('sexy'), regexp_replace(public.converge_norm('sexy'), '(.)\1+', '\1', 'g')),
  ('sexual', public.converge_norm('sexual'), regexp_replace(public.converge_norm('sexual'), '(.)\1+', '\1', 'g')),
  ('sexually', public.converge_norm('sexually'), regexp_replace(public.converge_norm('sexually'), '(.)\1+', '\1', 'g')),
  ('sexuality', public.converge_norm('sexuality'), regexp_replace(public.converge_norm('sexuality'), '(.)\1+', '\1', 'g')),
  ('shaved beaver', public.converge_norm('shaved beaver'), regexp_replace(public.converge_norm('shaved beaver'), '(.)\1+', '\1', 'g')),
  ('shaved pussy', public.converge_norm('shaved pussy'), regexp_replace(public.converge_norm('shaved pussy'), '(.)\1+', '\1', 'g')),
  ('shemale', public.converge_norm('shemale'), regexp_replace(public.converge_norm('shemale'), '(.)\1+', '\1', 'g')),
  ('shibari', public.converge_norm('shibari'), regexp_replace(public.converge_norm('shibari'), '(.)\1+', '\1', 'g')),
  ('shit', public.converge_norm('shit'), regexp_replace(public.converge_norm('shit'), '(.)\1+', '\1', 'g')),
  ('shitblimp', public.converge_norm('shitblimp'), regexp_replace(public.converge_norm('shitblimp'), '(.)\1+', '\1', 'g')),
  ('shitty', public.converge_norm('shitty'), regexp_replace(public.converge_norm('shitty'), '(.)\1+', '\1', 'g')),
  ('shota', public.converge_norm('shota'), regexp_replace(public.converge_norm('shota'), '(.)\1+', '\1', 'g')),
  ('shrimping', public.converge_norm('shrimping'), regexp_replace(public.converge_norm('shrimping'), '(.)\1+', '\1', 'g')),
  ('skeet', public.converge_norm('skeet'), regexp_replace(public.converge_norm('skeet'), '(.)\1+', '\1', 'g')),
  ('slanteye', public.converge_norm('slanteye'), regexp_replace(public.converge_norm('slanteye'), '(.)\1+', '\1', 'g')),
  ('slut', public.converge_norm('slut'), regexp_replace(public.converge_norm('slut'), '(.)\1+', '\1', 'g')),
  ('s&m', public.converge_norm('s&m'), regexp_replace(public.converge_norm('s&m'), '(.)\1+', '\1', 'g')),
  ('smut', public.converge_norm('smut'), regexp_replace(public.converge_norm('smut'), '(.)\1+', '\1', 'g')),
  ('snatch', public.converge_norm('snatch'), regexp_replace(public.converge_norm('snatch'), '(.)\1+', '\1', 'g')),
  ('snowballing', public.converge_norm('snowballing'), regexp_replace(public.converge_norm('snowballing'), '(.)\1+', '\1', 'g')),
  ('sodomize', public.converge_norm('sodomize'), regexp_replace(public.converge_norm('sodomize'), '(.)\1+', '\1', 'g')),
  ('sodomy', public.converge_norm('sodomy'), regexp_replace(public.converge_norm('sodomy'), '(.)\1+', '\1', 'g')),
  ('spastic', public.converge_norm('spastic'), regexp_replace(public.converge_norm('spastic'), '(.)\1+', '\1', 'g')),
  ('spic', public.converge_norm('spic'), regexp_replace(public.converge_norm('spic'), '(.)\1+', '\1', 'g')),
  ('splooge', public.converge_norm('splooge'), regexp_replace(public.converge_norm('splooge'), '(.)\1+', '\1', 'g')),
  ('splooge moose', public.converge_norm('splooge moose'), regexp_replace(public.converge_norm('splooge moose'), '(.)\1+', '\1', 'g')),
  ('spooge', public.converge_norm('spooge'), regexp_replace(public.converge_norm('spooge'), '(.)\1+', '\1', 'g')),
  ('spread legs', public.converge_norm('spread legs'), regexp_replace(public.converge_norm('spread legs'), '(.)\1+', '\1', 'g')),
  ('spunk', public.converge_norm('spunk'), regexp_replace(public.converge_norm('spunk'), '(.)\1+', '\1', 'g')),
  ('strap on', public.converge_norm('strap on'), regexp_replace(public.converge_norm('strap on'), '(.)\1+', '\1', 'g')),
  ('strapon', public.converge_norm('strapon'), regexp_replace(public.converge_norm('strapon'), '(.)\1+', '\1', 'g')),
  ('strappado', public.converge_norm('strappado'), regexp_replace(public.converge_norm('strappado'), '(.)\1+', '\1', 'g')),
  ('strip club', public.converge_norm('strip club'), regexp_replace(public.converge_norm('strip club'), '(.)\1+', '\1', 'g')),
  ('style doggy', public.converge_norm('style doggy'), regexp_replace(public.converge_norm('style doggy'), '(.)\1+', '\1', 'g')),
  ('suck', public.converge_norm('suck'), regexp_replace(public.converge_norm('suck'), '(.)\1+', '\1', 'g')),
  ('sucks', public.converge_norm('sucks'), regexp_replace(public.converge_norm('sucks'), '(.)\1+', '\1', 'g')),
  ('suicide girls', public.converge_norm('suicide girls'), regexp_replace(public.converge_norm('suicide girls'), '(.)\1+', '\1', 'g')),
  ('sultry women', public.converge_norm('sultry women'), regexp_replace(public.converge_norm('sultry women'), '(.)\1+', '\1', 'g')),
  ('swastika', public.converge_norm('swastika'), regexp_replace(public.converge_norm('swastika'), '(.)\1+', '\1', 'g')),
  ('swinger', public.converge_norm('swinger'), regexp_replace(public.converge_norm('swinger'), '(.)\1+', '\1', 'g')),
  ('tainted love', public.converge_norm('tainted love'), regexp_replace(public.converge_norm('tainted love'), '(.)\1+', '\1', 'g')),
  ('taste my', public.converge_norm('taste my'), regexp_replace(public.converge_norm('taste my'), '(.)\1+', '\1', 'g')),
  ('tea bagging', public.converge_norm('tea bagging'), regexp_replace(public.converge_norm('tea bagging'), '(.)\1+', '\1', 'g')),
  ('threesome', public.converge_norm('threesome'), regexp_replace(public.converge_norm('threesome'), '(.)\1+', '\1', 'g')),
  ('throating', public.converge_norm('throating'), regexp_replace(public.converge_norm('throating'), '(.)\1+', '\1', 'g')),
  ('thumbzilla', public.converge_norm('thumbzilla'), regexp_replace(public.converge_norm('thumbzilla'), '(.)\1+', '\1', 'g')),
  ('tied up', public.converge_norm('tied up'), regexp_replace(public.converge_norm('tied up'), '(.)\1+', '\1', 'g')),
  ('tight white', public.converge_norm('tight white'), regexp_replace(public.converge_norm('tight white'), '(.)\1+', '\1', 'g')),
  ('tit', public.converge_norm('tit'), regexp_replace(public.converge_norm('tit'), '(.)\1+', '\1', 'g')),
  ('tits', public.converge_norm('tits'), regexp_replace(public.converge_norm('tits'), '(.)\1+', '\1', 'g')),
  ('titties', public.converge_norm('titties'), regexp_replace(public.converge_norm('titties'), '(.)\1+', '\1', 'g')),
  ('titty', public.converge_norm('titty'), regexp_replace(public.converge_norm('titty'), '(.)\1+', '\1', 'g')),
  ('tongue in a', public.converge_norm('tongue in a'), regexp_replace(public.converge_norm('tongue in a'), '(.)\1+', '\1', 'g')),
  ('topless', public.converge_norm('topless'), regexp_replace(public.converge_norm('topless'), '(.)\1+', '\1', 'g')),
  ('tosser', public.converge_norm('tosser'), regexp_replace(public.converge_norm('tosser'), '(.)\1+', '\1', 'g')),
  ('towelhead', public.converge_norm('towelhead'), regexp_replace(public.converge_norm('towelhead'), '(.)\1+', '\1', 'g')),
  ('tranny', public.converge_norm('tranny'), regexp_replace(public.converge_norm('tranny'), '(.)\1+', '\1', 'g')),
  ('tribadism', public.converge_norm('tribadism'), regexp_replace(public.converge_norm('tribadism'), '(.)\1+', '\1', 'g')),
  ('tub girl', public.converge_norm('tub girl'), regexp_replace(public.converge_norm('tub girl'), '(.)\1+', '\1', 'g')),
  ('tubgirl', public.converge_norm('tubgirl'), regexp_replace(public.converge_norm('tubgirl'), '(.)\1+', '\1', 'g')),
  ('tushy', public.converge_norm('tushy'), regexp_replace(public.converge_norm('tushy'), '(.)\1+', '\1', 'g')),
  ('twat', public.converge_norm('twat'), regexp_replace(public.converge_norm('twat'), '(.)\1+', '\1', 'g')),
  ('twink', public.converge_norm('twink'), regexp_replace(public.converge_norm('twink'), '(.)\1+', '\1', 'g')),
  ('twinkie', public.converge_norm('twinkie'), regexp_replace(public.converge_norm('twinkie'), '(.)\1+', '\1', 'g')),
  ('two girls one cup', public.converge_norm('two girls one cup'), regexp_replace(public.converge_norm('two girls one cup'), '(.)\1+', '\1', 'g')),
  ('undressing', public.converge_norm('undressing'), regexp_replace(public.converge_norm('undressing'), '(.)\1+', '\1', 'g')),
  ('upskirt', public.converge_norm('upskirt'), regexp_replace(public.converge_norm('upskirt'), '(.)\1+', '\1', 'g')),
  ('urethra play', public.converge_norm('urethra play'), regexp_replace(public.converge_norm('urethra play'), '(.)\1+', '\1', 'g')),
  ('urophilia', public.converge_norm('urophilia'), regexp_replace(public.converge_norm('urophilia'), '(.)\1+', '\1', 'g')),
  ('vagina', public.converge_norm('vagina'), regexp_replace(public.converge_norm('vagina'), '(.)\1+', '\1', 'g')),
  ('venus mound', public.converge_norm('venus mound'), regexp_replace(public.converge_norm('venus mound'), '(.)\1+', '\1', 'g')),
  ('viagra', public.converge_norm('viagra'), regexp_replace(public.converge_norm('viagra'), '(.)\1+', '\1', 'g')),
  ('vibrator', public.converge_norm('vibrator'), regexp_replace(public.converge_norm('vibrator'), '(.)\1+', '\1', 'g')),
  ('violet wand', public.converge_norm('violet wand'), regexp_replace(public.converge_norm('violet wand'), '(.)\1+', '\1', 'g')),
  ('vorarephilia', public.converge_norm('vorarephilia'), regexp_replace(public.converge_norm('vorarephilia'), '(.)\1+', '\1', 'g')),
  ('voyeur', public.converge_norm('voyeur'), regexp_replace(public.converge_norm('voyeur'), '(.)\1+', '\1', 'g')),
  ('voyeurweb', public.converge_norm('voyeurweb'), regexp_replace(public.converge_norm('voyeurweb'), '(.)\1+', '\1', 'g')),
  ('voyuer', public.converge_norm('voyuer'), regexp_replace(public.converge_norm('voyuer'), '(.)\1+', '\1', 'g')),
  ('vulva', public.converge_norm('vulva'), regexp_replace(public.converge_norm('vulva'), '(.)\1+', '\1', 'g')),
  ('wank', public.converge_norm('wank'), regexp_replace(public.converge_norm('wank'), '(.)\1+', '\1', 'g')),
  ('wetback', public.converge_norm('wetback'), regexp_replace(public.converge_norm('wetback'), '(.)\1+', '\1', 'g')),
  ('wet dream', public.converge_norm('wet dream'), regexp_replace(public.converge_norm('wet dream'), '(.)\1+', '\1', 'g')),
  ('white power', public.converge_norm('white power'), regexp_replace(public.converge_norm('white power'), '(.)\1+', '\1', 'g')),
  ('whore', public.converge_norm('whore'), regexp_replace(public.converge_norm('whore'), '(.)\1+', '\1', 'g')),
  ('worldsex', public.converge_norm('worldsex'), regexp_replace(public.converge_norm('worldsex'), '(.)\1+', '\1', 'g')),
  ('wrapping men', public.converge_norm('wrapping men'), regexp_replace(public.converge_norm('wrapping men'), '(.)\1+', '\1', 'g')),
  ('wrinkled starfish', public.converge_norm('wrinkled starfish'), regexp_replace(public.converge_norm('wrinkled starfish'), '(.)\1+', '\1', 'g')),
  ('xx', public.converge_norm('xx'), regexp_replace(public.converge_norm('xx'), '(.)\1+', '\1', 'g')),
  ('xxx', public.converge_norm('xxx'), regexp_replace(public.converge_norm('xxx'), '(.)\1+', '\1', 'g')),
  ('yaoi', public.converge_norm('yaoi'), regexp_replace(public.converge_norm('yaoi'), '(.)\1+', '\1', 'g')),
  ('yellow showers', public.converge_norm('yellow showers'), regexp_replace(public.converge_norm('yellow showers'), '(.)\1+', '\1', 'g')),
  ('yiffy', public.converge_norm('yiffy'), regexp_replace(public.converge_norm('yiffy'), '(.)\1+', '\1', 'g')),
  ('zoophilia', public.converge_norm('zoophilia'), regexp_replace(public.converge_norm('zoophilia'), '(.)\1+', '\1', 'g')),
  ('🖕', public.converge_norm('🖕'), regexp_replace(public.converge_norm('🖕'), '(.)\1+', '\1', 'g'))
on conflict (word) do nothing;
delete from public.banned_words where length(norm) < 3;
